server:
  port: 8080

spring:
  profiles:
    #    active: dev
    active: prod
  application:
    name: Registration Management

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        show_sql: false

  flyway:
    baseline-on-migrate: true
    table: SCHEMA_HISTORY
    locations:
      - classpath:/db/migration
      - classpath:/db/migration-data

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher



