
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:~/DATA2
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      path: /h2
      enabled: true


