
spring:

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      path: /h2
      enabled: true
  main:
    allow-bean-definition-overriding: true