server:
  port: 8081

spring:
  datasource:
    #    url: jdbc:h2:file:~/registration-management
    url: jdbc:h2:mem:registration-management;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    properties:
      hibernate:
        use_sql_comments: true
        show_sql: true
        format_sql: true

#  flyway:
#    baseline-on-migrate: true
#    table: SCHEMA_HISTORY
#    locations:
#      - classpath:/db/migration
#      - classpath:/db/migration-data