server:
  port: 8080

spring:
  application:
    name: Registration Management

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        show_sql: false

    table: SCHEMA_HISTORY

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher



