spring:
  datasource:
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
#    username: ${DB_USER}
#    password: ${DB_SECRET}
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/registration-management
    username: postgres
    password: root
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
